### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Sashimi0343** [Sashimi0343/protospace-35172#1]
本番環境での 提出前動作確認 は終了致しました。
抜け漏れ等が無いか最終確認をお願い致します。

以下URL
https://protospace-35172.herokuapp.com/

**Comment by snkw-works** [comment]
@Sashimi0343 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
ユーザー名が正しく表示されていない状態です。
<img width="1435" alt="スクリーンショット_2021-05-16_13_01_29" src="https://user-images.githubusercontent.com/54050089/118385096-06537c80-b647-11eb-8c46-8a349ecad5ac.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Sashimi0343** [comment]
課題の確認、ありがとうございます。
ご指摘頂いた箇所の修正を行いましたので、再度確認をお願い致します。
お手数おかけしますが、何卒宜しくお願い致します。

以下URL
https://protospace-35172.herokuapp.com/

**Comment by snkw-works** [comment]
@Sashimi0343 さん、ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
